//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeProject.Business.Entities
{
    using System;
    using System.Collections.Generic;

 
    public partial class contentRight
    {
     
        public long id { get; set; }
        public long group_id { get; set; }
        public long content_type_id { get; set; }
        public long content_id { get; set; }
        public long right_id { get; set; }
    
        public virtual contentType contentType { get; set; }
        public virtual group group { get; set; }
        public virtual rightType rightType { get; set; }
    }
}
