//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeProject.Business.Entities
{
    using System;
    using System.Collections.Generic;


    public class Document
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string NameOnServer { get; set; }
        public string Extension { get; set; }
        public long? ContentId { get; set; }
        public long ParentDocumentId { get; set; }
        public DateTime Created { get; set; }
        public long ContentTypeId { get; set; }
        public string ContentTypeName { get; set; }
    }
}
