//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeProject.Business.Entities
{
    using System;
    using System.Collections.Generic;
    

    public partial class group
    {
        public group()
        {
            this.contentRights = new HashSet<contentRight>();
            this.userGroups = new HashSet<userGroup>();
        }
  
        public long id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public long group_type_id { get; set; }
    
        public virtual ICollection<contentRight> contentRights { get; set; }
        public virtual groupType groupType { get; set; }
        public virtual ICollection<userGroup> userGroups { get; set; }
    }
}
