//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeProject.Business.Entities
{
    using System;
    using System.Collections.Generic;
    

    public class Group
    {
       
        public long Id { get; set; }
        public String Name { get; set; }
        public String Email { get; set; }
        public long GroupTypeId { get; set; }
    
    }
}
