//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeProject.Business.Entities
{
    using System;
    using System.Collections.Generic;

    public partial class statusTranslation
    {
        public statusTranslation()
        {
            this.actionTypes = new HashSet<ActionType>();
        }

       
        public long id { get; set; }
        public long status_id_from { get; set; }
        public long status_id_to { get; set; }
    
        public virtual ICollection<ActionType> actionTypes { get; set; }
        public virtual status status { get; set; }
        public virtual status status1 { get; set; }
    }
}
