//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeProject.Business.Entities
{
    using System;
    using System.Collections.Generic;

    public class Status
    {
       
        public long Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<StatusTranslation> statusTranslations { get; set; }
        public virtual ICollection<StatusTranslation> statusTranslations1 { get; set; }
    }
}
