//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeProject.Business.Entities
{
    using System;
    using System.Collections.Generic;

    public partial class status
    {
        public status()
        {
            this.statusTranslations = new HashSet<statusTranslation>();
            this.statusTranslations1 = new HashSet<statusTranslation>();
        }

           public long id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<statusTranslation> statusTranslations { get; set; }
        public virtual ICollection<statusTranslation> statusTranslations1 { get; set; }
    }
}
