//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeProject.Business.Entities
{
    using System;
    using System.Collections.Generic;

   
    public class user
    {
        public user()
        {
            this.actions = new HashSet<Action>();
            this.userGroups = new HashSet<userGroup>();
            this.workflows = new HashSet<workflow>();
        }

    
        public long id { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public bool is_active { get; set; }
        public System.DateTime created { get; set; }
        public string created_by { get; set; }
    
        public virtual ICollection<Action> actions { get; set; }
        public virtual ICollection<userGroup> userGroups { get; set; }
        public virtual ICollection<workflow> workflows { get; set; }
    }
}
