//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeProject.Business.Entities
{
    using System;
    using System.Collections.Generic;


    public partial class workflow
    {
        public workflow()
        {
            this.actions = new HashSet<Action>();
            this.actions1 = new HashSet<Action>();
        }


        public long id { get; set; }
        public string name { get; set; }
        public string case_number { get; set; }
        public long workflow_type_id { get; set; }
        public Nullable<long> last_action_id { get; set; }
        public System.DateTime created { get; set; }
        public long created_by { get; set; }
        public bool is_deleted { get; set; }
    
        public virtual ICollection<Action> actions { get; set; }
        public virtual ICollection<Action> actions1 { get; set; }
        public virtual user user { get; set; }
        public virtual workflowType workflowType { get; set; }
    }
}
